version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fittrack
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fittrack
      - MYSQL_USER=fituser
      - MYSQL_PASSWORD=fitpassword

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mysql  
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/fittrack
      - MYSQL_URI=mysql://fituser:fitpassword@mysql:3306/fittrack
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=3000
      - FAST_REFRESH=false
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
  mysql_data: